/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {

  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  guide: [{type: 'autogenerated', dirName: 'guide'}],  // foldername
  api: [{type: 'autogenerated', dirName: 'api'}],  // foldername
};

module.exports = sidebars;